### ISSUE TITLE
SLC Driver I/O tag pattern match looking for group 'file_number' which is not part of regex

### ISSUE THREAD

**Issue by acedrew** [ottowayi/pycomm3#137]
I know SLC support isn't your focus, but there are a lot of these legacy devices still out there. I'll be working on fixing this, but just wanted to document it here as well.

https://github.com/ottowayi/pycomm3/blob/b6256d8e0e203c2d123bfe30760ad28b8fc4c37b/pycomm3/slc_driver.py#L457

**Comment by ottowayi** [comment]
Thanks for finding it, yeah that is a bug.  `(?P<file_number>\d{1,3})` should be included before the colon.  If you want to fix it and make a PR I will merge it.  I have been planning on re-writing the driver so I can better support it (right now it's a mess and difficult to debug), but I'm not going to be able to get to it for awhile.   I'm in the process of moving right now, so all my free time is taken up getting my house ready to sell and packing.   But long-term I plan on supporting it since I get a lot of requests for MicroLogix devices.
