### ISSUE TITLE
[BUG] - Array of Strings interpreted as String of Fixed Length

### ISSUE THREAD

**Issue by OctavianGauss** [ottowayi/pycomm3#163]
**Pre-checks**
- [ X] running latest version
- [ X] enabled logging 
- [ X] consulted the [docs](https://pycomm3.readthedocs.io/en/latest/) 

**Description**
When I'm accessing a tag that is an array of 16 strings from the plc, the tag data does not come back as an array of strings, but as a string of fixed length 16. I should be able to use my mini GUI to burrow down into each of the 16 strings. Thank you for looking into this.

**Target PLC**
Model:  5069-L320ERS2
Firmware Revision: 33

**Code Sample**
```
from pycomm3 import *
import tkinter as tk
from tkinter import ttk
from pycomm3.logger import configure_default_logger

configure_default_logger(filename='c:/tmp/pycomm3.log')

class MainWindow(tk.Tk):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.host_address = '10.10.150.10' #Change to fit needs
        self.comm = LogixDriver(f'{self.host_address}', init_tags=True)
        
        self.container_frame = tk.Frame(self)
        self.container_frame.columnconfigure(0, weight=1)
        self.container_frame.rowconfigure(0, weight=1)
        self.container_frame.grid(row=0, column=0, sticky="NSEW")
        
        self.tree = ttk.Treeview(self.container_frame, show="tree")
        self.tree.grid(row=0, column=0, sticky="NSEW")
        self.y_tree_scroll = ttk.Scrollbar(self.container_frame, orient="vertical", command=self.tree.yview)
        self.tree.configure(yscrollcommand=self.y_tree_scroll.set)
        self.y_tree_scroll.grid(row=0, column=1, sticky="NS")
        
        self.get_tags_button = ttk.Button(self.container_frame, text="Get Tags", command=self.populate_tree)
        self.get_tags_button.grid(row=1, columnspan=2)


    def populate_tree(self):
        """Creates tag hierarchy in Treeview"""
        self.comm.open()
        self.add_node(self.tree, '', self.comm.tags)
        self.tree.heading("#0")
        self.treeview_sort_column(self.tree, "#0", False)
        self.comm.close()

    def add_node(self, tree, parent, dictionary):
        for key in dictionary:
            if isinstance(dictionary[key], dict):
                if "data_type_name" in dictionary[key]:
                    if dictionary[key]['tag_type'] == "atomic":
                        tree.insert(parent, 'end', f'{parent}.{key}',
                                    text=f'{key}    {dictionary[key]["data_type_name"]}')
                        self.add_node(tree, f'{parent}.{key}', dictionary[key])
                    elif dictionary[key]['tag_type'] == 'struct':
                        if dictionary[key]["data_type_name"] == "STRING":
                            tree.insert(parent, 'end', f'{parent}.{key}', text=f'{key}    STRING')
                            self.add_node(tree, f'{parent}.{key}', dictionary[key])
                        else:
                            tree.insert(parent, 'end', f'{parent}.{key}', text=f'{key}    STRUCTURE')
                            self.add_node(tree, f'{parent}.{key}', dictionary[key])
                else:
                    tree.insert(parent, 'end', f'{parent}.{key}', text=f'{key}')
                    self.add_node(tree, f'{parent}.{key}', dictionary[key])

    def treeview_sort_column(self, tv, col, reverse):
        to_sort = [(tv.item(k)["text"], k) for k in tv.get_children()]
        to_sort.sort(key=lambda t: t[0], reverse=reverse)

        for index, (val, k) in enumerate(to_sort):
            tv.move(k, '', index)

        tv.heading(col, command=lambda: self.treeview_sort_column(tv, col, not reverse))


root = MainWindow()
root.columnconfigure(0, weight=1)
root.rowconfigure(0, weight=1)
root.mainloop()
```

**Additional context**
 The tag is an array of 16 Strings
 
[pycomm3.log](https://github.com/ottowayi/pycomm3/files/6976827/pycomm3.log)
![Terminal Example](https://user-images.githubusercontent.com/59286525/129229226-b54e7e1c-fc65-4ae6-936e-bc1bb7598600.JPG)
![Treeview Example](https://user-images.githubusercontent.com/59286525/129229238-2c4631a2-6fb1-4762-bacc-d091b6fdf9ea.JPG)

**Comment by ottowayi** [comment]
The terminal output looks correct, I think you're just misinterpreting it.   The `dim` shows how many array dimensions the tag has.   Normal tags it will be zero, here it's `1` indication this tag is an array with 1 dimension.   The `dimensions` attribute is the size of each dimension, 0 means the dimension does not exist.   The attributes for a tag are documented [here](https://docs.pycomm3.dev/en/latest/usage/logixdriver.html#tag-structure)

 The `type_class` is a pycomm3 [tag type](https://docs.pycomm3.dev/en/latest/api_reference/data_types.html#module-pycomm3.cip.data_types) that is used to encode and decode the value of the tag, `FixedSizeString[16]` means it's a array of 16 `FixedSizedString`.  There is a difference between a CIP STRING type and a Logix tag STRING, that's why the internal type is called `FixedSizedString` instead of just `STRING`.   I think you will need to extend your `add_node` function to check the dimensions and create node for each element in the array if that is what you want displayed.

**Comment by GitHubDragonFly** [comment]
@OctavianGauss 

You could also try testing the [GUI example](https://github.com/ottowayi/pycomm3/blob/master/examples/lgx_gui_test.py) and if it shows everything properly then check its code.

**Comment by OctavianGauss** [comment]
@ottowayi

Wow, thanks for responding so quickly. I very likely am misinterpreting it. I was confused by the lack of sub-data.

@GitHubDragonFly 

Thanks for the suggestion. It doesn't display things in the way I need it, but I may still be able to use it to improve my code.

**Comment by ottowayi** [comment]
For structures you'll see a bunch of sub-tags, but arrays are really only a single tag with 1-3 dimensions. The `tags` property also is only information about the tags, it doesn't contain any of the values.   It doesn't do that by default due to just the time it would take to read every tag, plus any issues with revolving around external access.  If you need any help getting it to display the arrays correctly, feel free to reopen or comment here and I'll try to help get it figured out.

**Comment by OctavianGauss** [comment]
Thanks, yes I'm having some issues still parsing the arrays correctly. Mostly I'm concerned about sub-information, such as length of each string in an array of strings. Or such as arrays of UDTs. I haven't tried it yet, but I'm assuming I wouldn't be able to access the sub-tags without building a UDT by UDT profile in your code.

**Comment by ottowayi** [comment]
So I would approach arrays separate from the structures/UDTs.   Arrays at the simplest idea are a way of duplicating a tag.  You define a tag whether it be a simple DINT or a complicated UDT, that definition doesn't change if it's a single tag or an array of them.  Implementing an array then is just looking at that tag's dimensions and making that many copies of it.   This also applies to UDTs or other structures, all the information about sub-tags is defined on the main tag totally separate from whether that tag is an array or not.  For structures (`tag_type == 'struct'`) , the `internal_tags` field will be another dictionary with definitions for each sub-tag.  Each internal tag definition includes an `'array'` field indicating the length of the array (0 means it's not an array). That is because you can only have 1-dimension arrays inside a struct.  It also includes private tags that you won't see inside Logix, you can use the `'attributes'` field to filter only the Logix-viewable tags, it is a list of the visible sub-tags. 

Here is a snippet of a nested UDT's definition I grabbed from the test data
```
 "write_nested_udt1": {
        "dim": 0,
        "alias": false,
        "dimensions": [0,0,0 ],
        "tag_type": "struct",
        "data_type": {
            "name": "pycomm3_NestedUDT",
            "internal_tags": {
                "udt1": {
                    "offset": 0,
                    "tag_type": "struct",
                    "data_type": {
                        "name": "pycomm3_AtomicUDT",
                        "internal_tags": {
                            "ZZZZZZZZZZpycomm3_At0": {
                                "tag_type": "atomic",
                                "data_type": "SINT",
                                "data_type_name": "SINT",
                                "array": 0
                            },
                            "bool": {
                                "tag_type": "atomic",
                                "data_type": "BOOL",
                                "data_type_name": "BOOL",
                                "bit": 0
                            },
                            ...
                        "attributes": ["bool", ...],
                 "udt2": {
                    "tag_type": "struct",
                    "data_type": {
                        "name": "pycomm3_AtomicArrayUDT",
                        "internal_tags": {
                            "bools": {
                                "tag_type": "atomic",
                                "data_type": "DWORD",
                                "data_type_name": "DWORD",
                                "array": 2
                            },
                            "sints": {
                                "tag_type": "atomic",
                                "data_type": "SINT",
                                "data_type_name": "SINT",
                                "array": 8
                            },
                        "attributes": ["bools", "sints", ...]
            ...
            "attributes": ["udt1", "udt2", ...]
```

Strings are sort of a special case, they're technically structures like UDTs, but we treat them as atomic types for convenience.  Any struct that contains only a LEN(DINT) and DATA(Array of SINT) attributes will be treated as a STRING type, the tag info will have a `string` attribute that contains the total length of a string. 

Here is part of a custom string definition:
```
{
"name": "STRING480",
"internal_tags": {
    "LEN": {
        "offset": 0,
        "tag_type": "atomic",
        "data_type": "DINT",
        "data_type_name": "DINT",
        "array": 0
    },
    "DATA": {
        "offset": 4,
        "tag_type": "atomic",
        "data_type": "SINT",
        "data_type_name": "SINT",
        "array": 480
    }
},
"attributes": [
    "LEN",
    "DATA"
],
"string": 480,
...
```

You can see it has a `'string'` field with a value of 480, that means this is a STRING type with a length of 480.  Tags that are missing the `'string'` field will not be considered strings by pycomm3. 

Hopefully that is some help, also the documentation also includes some explanations of what each field means [here](https://docs.pycomm3.dev/en/latest/usage/logixdriver.html#tag-structure).
