### ISSUE TITLE
Logic to allow logix_driver.write and .read to accept a list/tuple of (tag, value)

### ISSUE THREAD

**Issue by gis667en11** [ottowayi/pycomm3#244]
### Discussed in https://github.com/ottowayi/pycomm3/discussions/243

<div type='discussions-op-text'>

<sup>Originally posted by **gis667en11** September 29, 2022</sup>
Hello! I made a quick modification to allow the write() method to accept an array of tuples.

`if len(tags_values) == 1 and isinstance(tags_values[0], Union[tuple,list]):`
. . . . `tags_values = tags_values[0]`

This going just before the "if len(tags_values) == 2" around line 1050. I'm not certain how to do pull requests, but this change allowed me to do things like this:

`strings = [ 'tag.msgData.timeSinceLastReceipt_ms',`
. . . . `'tag.msgData.timeSinceLastUpdate_ms',`
. . . . `'tag.msgData.receiptCount',`
. . . . `'tag.state_Start',`
. . . . `'tag.state_Standby',`
. . . . `'tag.coordinate_X',`
. . . . `'tag.coordinate_Y']`

`svalues = [45, 555, 789, True, False, 3.14, 8008.135]`

`writeTags = zip(strings,svalues)`

`with pycomm3.LogixDriver('192.168.1.10') as plc:`
. . . . `plc.write(writeTags)`

Or something fancy like this:

`writeTags = []`

`if ButtonPressed:`
. . . . `buttonCount += 1`
. . . . `writeTags.extend( ('tag.ButtonCount', buttonCount) )`

`if updateTempAlarm:`
. . . . `if TemperatureHigh:`
. . . . . . . . `writeTags.extend( ('tag.tempAlarm', True)`
. . . . `else:`
. . . . . . . . `writeTags.extend( ('tag.tempAlarm', False)`

`if writeTags:`
. . . . `with pycomm3.LogixDriver('192.168.1.10') as plc:`
. . . . . . . . `plc.write(writeTags)`

So, the write method would either write to the ButtonCount integer AND update the tempAlarm bool, OR just the tempAlarm bool, OR would write nothing at all.

With this method, the multi-service request feature of the write method can be leveraged while allowing a dynamic set of tags as an input. which is otherwise impossible with the current code.

The same is also possible by adding this to the .read() method:

`if len(tags) == 1 and isinstance(tags[0], Union[tuple,list]):`
. . . . `tags = tags[0]`

**Comment by ottowayi** [comment]
I chose to make `tags` variable length so that I would not have to inspect the object to check if it were multiple tags or just one, they'd always be treated the same.  Perhaps this was the wrong choice, but it made my life easier at the time.  I think both issues can be resolved by unpacking the list like was mentioned in the discussion, but I do not think you'd require a if-statement.  

Since you start with `writeTags = []` and you can append tag/value tuples to it and then can always `plc.write(*writeTags)`.  Using `list.extend` here I think is causing you an issue, I'm assuming you want to set `tag.tempAlarm` to true/false in the example.  But, `extend` is not adding the tuple to the list, it iterates over the tuple and adds each item to the list.  For example, notice what happens with the 3's:

```py
>>> x = [(1,1), (2,2)]
>>> x.extend((3,3))
>>> x
[(1, 1), (2, 2), 3, 3] 
>>> x.append((4,4))
>>> x
[(1, 1), (2, 2), 3, 3, (4, 4)]
```
