### ISSUE TITLE
pycomm3 vs pycomm

### ISSUE THREAD

**Issue by AndrewStuhr** [ottowayi/pycomm3#53]
Hi

I see on the main page that pycomm3 is a fork of pycomm.  Did you add a bunch of features that aren't in pycomm?  I'm trying to use pycomm to read micrologix tags, and it seems like all it does is read and write, there's no tag discovery.

Thanks!

**Comment by ottowayi** [comment]
It started as a fork of pycomm, since pycomm was written in Python 2.  I used the fork linked in the readme as the original base code since they had started the Python 3 translation.  Since then I've rewritten most of the code and restructured a lot of the modules.  I started this as a side project to the app I develop for my company to setup/configure/commission/etc our AOIs.  We have a system similar to PlantPAx, but my app is more automated and easier to use.  At the time it only used OPC with RSLinx (which is a whole bucket of issues on it's own) and required importing an L5X to get all of the tags/data-types.  I found pycomm and it seemed perfect for our needs.  I've not developed the SLC/MLX driver at all since our system is AOI based and will never run on the old hardware.  They use a different protocol and a lot of the features are just can't be done in it.  I've left the module in there in case anyone would like to update it, but I haven't had the time to devote to it since it's not going to be used by us.  The biggest features I've added would be reducing the different read/write methods to just a single read and write to handle all the possible data types.  They automatically manage the request and response size to pack as many requests in a single packet, it will automatically use fragmented services if the tags are too large to fit in a single packet, and the full structure read and write.  That being said, there is no way I would have been able to do this from scratch.  The pycomm developers did all the hard work, I've mostly taken their code and refactored or extended it. 

So, to answer your original question.. I don't believe there are any other features that can be added besides the just the ability to read and write the data file elements.  They use the older PCCC protocol and it just doesn't have the features the CIP does.
