### ISSUE TITLE
Reconnect to PLC after broken interrupted

### ISSUE THREAD

**Issue by gersontsouza** [ottowayi/pycomm3#60]
Hi,

I need to read some PLC tags periodically, for example, inside a while loop, like the example below:

```
from pycomm3 import LogixDriver
import time

plc = LogixDriver('192.168.1.210/2')

while(True):
    tag_read = plc.read('DateTime[5]')
    print(time.ctime(), tag_read)
    time.sleep(1.0)
```

If the connection is interrupted, for example, by a problem on the network, the tag value returns as None, as expected
But when the PLC is again available, the following error messages are reported:

Wed Jul 29 20:48:09 2020 DateTime[5], 6, DINT, None
Wed Jul 29 20:48:10 2020 DateTime[5], 7, DINT, None
Wed Jul 29 20:48:16 2020 DateTime[5], None, None, timed out
Wed Jul 29 20:48:22 2020 DateTime[5], None, None, timed out
Wed Jul 29 20:48:28 2020 DateTime[5], None, None, timed out
Wed Jul 29 20:48:30 2020 DateTime[5], None, None, [WinError 10054] An existing connection was forcibly closed by the remote host
Wed Jul 29 20:48:31 2020 DateTime[5], None, None, socket connection broken.
Wed Jul 29 20:48:32 2020 DateTime[5], None, None, socket connection broken.
Wed Jul 29 20:48:33 2020 DateTime[5], None, None, socket connection broken.

Is there any configuration so that the socket connection is not closed, or that a new one is created?

Thanks

**Comment by ottowayi** [comment]
Right now, no there isn't anything like that in there.  I have been thinking about adding that option, but I haven't gotten to it yet. I would expect that an exception should be thrown and you would handle reconnecting from the application side, but I realized that the `read` method doesn't raise one.  I remember deciding that it would return a Tag list so that if only one of the requests failed, the others would at least be returned.  If I made a change that those type of exceptions are raised, how would you feel about catching it and handling the reconnection?  Right now it catches just the base Exception, but I could change it so that it only catches DataError and RequestError exceptions and any others would bubble up.
